---

- name: Create a handy development machine
  hosts: all
  become: true

  vars:
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: pass1234
    jenkins_plugins:
      - name: blueocean
      - name: workflow-aggregator
    jenkins_plugins_install_dependencies: true
    nexus_anonymous_access: true
    nexus_admin_password: pass1234
    nexus_default_port: 8081
    gitea_http_listen: 0.0.0.0
    gitea_http_port: 3000
    gitea_ssh_listen: 0.0.0.0
    gitea_ssh_port: 8222


  roles:
    - name: geerlingguy.docker
    - name: geerlingguy.java
    - name: geerlingguy.jenkins
    - name: geerlingguy.nodejs
    - name: geerlingguy.apache
    - name: ansible-thoteam.nexus3-oss
    - name: thomas_maurice.ansible_role_gitea

  tasks:
    - name: Install useful packages
      package:
        name:
          - vim
          - net-tools
          - git
        state: latest

    - name: Print hello whirled
      debug: msg="Hello whirled"
