---

- name: Create a handy development machine
  hosts: all
  become: true

  vars:
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: pass1234
    jenkins_plugins:
      - name: blueocean
      - name: workflow-aggregator
    jenkins_plugins_install_dependencies: true

  roles:
    - name: geerlingguy.docker
    - name: geerlingguy.java
    - name: geerlingguy.jenkins
    - name: geerlingguy.nodejs
    - name: geerlingguy.apache

  tasks:
    - name: Install useful packages
      package:
        name:
          - vim
          - net-tools
          - git
        state: latest

    - name: Print hello whirled
      debug: msg="Hello whirled"
