---
roles:
  - name: geerlingguy.java
  - name: geerlingguy.docker
  - name: geerlingguy.jenkins
  - name: geerlingguy.nodejs
  - name: geerlingguy.apache
  - name: ansible-thoteam.nexus3-oss
  - name: thomas_maurice.ansible_role_gitea
